= Communication requirements

This document specifies the communication requirements of the product.

== Parameters

[format="csv", options="header"]
|===
include::../../params/communication.csv[]
|===

== Requirements

=== WiFi Communication

The product shall act as a WiFi station.

=== WiFi Configuration

The WiFi configuration shall be configurable via the
<<diagnostics.adoc,diagnostic mode>>.

=== WiFi States

On power on reset the product shall act a WiFi Access Point for 
<<Parameters,param_wifi_ap_por_timeout>>, afterwards the product shall attempt
to connect to the configured WiFi Access Point as a Station. 

If the product is unable to connect within
<<Parameters,param_wifi_sta_connection_timeout>> then the product shall attempt
reconnecting after <<Parameters,param_wifi_sta_retry_timeout>>.

=== MQTT Communication

The product shall publish MQTT messages.

=== MQTT Configuration

The MQTT configuration shall be configurable via the
<<diagnostics.adoc,diagnostic mode>>.

=== MQTT States

After the product has successfully connected to the configured WiFi Access Point
it shall attempt to connect to the configured MQTT broker.

If the product is unable to connect within
<<Parameters,param_mqtt_connection_timeout>> then the product shall attempt
reconnecting after <<Parameters,param_mqtt_retry_tmeout>>.
