= Software communication

This document specifies the communication requirements of the software.

== Parameters

[format="csv", options="header"]
|===
include::system/params/communication.csv[]
|===

[format="csv", options="header"]
|===
include::software/params/communication.csv[]
|===

== Requirements

=== WiFi Communication

=== WiFi Configuration

The WiFi configuration shall be configurable via the
xref:diagnostics.adoc[diagnostic mode].

=== WiFi States

After power on reset the software shall detect if there's a problem initializing
the WiFi module and set the WiFi state to _MODULE_ERROR_.

After module initialization the software shall act a WiFi Access Point for 
<<Parameters,param_wifi_ap_por_timeout>> or more if there's an active client
connection, afterwards the software shall attempt to connect to the configured 
WiFi Access Point as a Station. 
If the WiFi isn't configured correctly (empty SSID) the software shall stay in
AP mode until configuration is set and the device is either reset or connection
is forced via diagnostic commands.

If the software is unable to connect <<Parameters,param_wifi_sta_connection_timeout>>
within then the software shall attempt reconnecting after
<<Parameters,param_wifi_sta_retry_timeout>>.

=== MQTT Communication

The software shall publish MQTT messages every <<Parameters,param_mqtt_publish_interval>>.

=== MQTT States

The software shall only attempt an MQTT connection once the WiFi connection
has been secured.

If the software is unable to connect within <<Parameters,param_mqtt_connection_timeout>>
then the software shall attempt reconnecting earliest after
<<Parameters,param_mqtt_retry_tmeout>>.
